[package]
name = "scc"
version = "0.5.1"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2021"
publish = false

[dependencies]
redscript = { path = "../core" }
redscript-compiler = { path = "../compiler" }
byteorder = "1.4"
vmap = { version = "0.5", default-features = false }
log = "0.4"
fern = "0.6"
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
fd-lock = "3.0"
msgbox = { version = "0.6", optional = true }

[features]
popup = ["msgbox"]

[package.metadata.release]
tag = false
