[package]
name = "redscript"
version = "0.1.0"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1.3"
num-derive = "0.3"
num-traits = "0.2"
