name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: copy cargo config
        run: xcopy /H /E /Y .\\.cargo C:\\Rust\\.cargo\
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features mmap,popup
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            target/release/scc.exe
            target/release/redscript-cli.exe
